### ISSUE TITLE
Otp Facebook

### ISSUE THREAD

**Issue by FerryVication** [MR-X-junior/fbthon#2]
Bang Kok OTP nya ga masuk-masuk ya pas create akun

**Comment by MR-X-junior** [comment]
Coba pake method `resend_code` untuk mengirim ulang kode OTP

**Comment by FerryVication** [comment]
dan kenapa pas create akun selalu checkpoint

**Comment by MR-X-junior** [comment]
> dan kenapa pas create akun selalu checkpoint

Agar akun terhindar dari checkpoint, kamu bisa coba 2 cara di bawah ini

- Ganti Alamat IP
- Ganti headers `CreateAccount`
   ```python
   new_account = CreateAccount(firstname = firstname, lastname = lastname, email = email, gender = gender, date_of_birth = ultah, password = sandi, headers = {'User-Agent':'User agent'})
   ```
